# Generated by Django 2.0.3 on 2018-03-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_desc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_desc',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(default='ABC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='no_of_beds',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
