# Generated by Django 2.0.3 on 2018-03-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180330_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_desc',
        ),
    ]
