# Generated by Django 2.0.3 on 2018-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180321_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Hospital'), (4, 'Admin')], null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
