# Generated by Django 2.0.3 on 2018-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180330_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(unique=True),
        ),
    ]
